# Generated by Django 6.0.4 on 2026-04-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="The ID of the defect report.", max_length=100
                    ),
                ),
                (
                    "retest_result",
                    models.TextField(help_text="The result of the retest."),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the retest result was submitted.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who submitted the retest result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
