# Generated by Django 5.2.12 on 2026-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=30)),
                ('Version', models.CharField(max_length=30)),
                ('ReportTitle', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Steps', models.TextField()),
                ('TesterID', models.CharField(max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Assigned', 'Assigned'), ('Cannot reproduce', 'Cannot reproduce'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened')], default='New', max_length=20)),
                ('Severity', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Low', 'Low')], max_length=20)),
                ('Priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('AssignedPerson', models.CharField(max_length=30)),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('UpdatedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
