# Generated by Django 6.0.4 on 2026-04-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductID",
                    models.CharField(
                        help_text="Unique identifier for the product associated.",
                        max_length=30,
                    ),
                ),
                (
                    "Version",
                    models.CharField(
                        help_text="The version of the product the report is applicable to.",
                        max_length=30,
                    ),
                ),
                (
                    "ReportTitle",
                    models.CharField(
                        help_text="A brief title for the defect report.", max_length=30
                    ),
                ),
                (
                    "Description",
                    models.CharField(
                        help_text="A detailed description of the defect.",
                        max_length=200,
                    ),
                ),
                (
                    "Steps",
                    models.TextField(help_text="The steps to reproduce the defect."),
                ),
                (
                    "TesterID",
                    models.CharField(
                        help_text="The ID of the tester who submitted the report.",
                        max_length=30,
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for the tester, optional.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Open", "Open"),
                            ("Rejected", "Rejected"),
                            ("Duplicate", "Duplicate"),
                            ("Assigned", "Assigned"),
                            ("Cannot reproduce", "Cannot reproduce"),
                            ("Fixed", "Fixed"),
                            ("Resolved", "Resolved"),
                            ("Reopened", "Reopened"),
                        ],
                        default="New",
                        help_text="Current status of the defect report.",
                        max_length=20,
                    ),
                ),
                (
                    "Severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Critical", "Critical"),
                            ("Major", "Major"),
                            ("Minor", "Minor"),
                            ("Low", "Low"),
                        ],
                        help_text="The severity level of the defect.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        help_text="The priority level of the defect.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("CreatedTime", models.DateTimeField(auto_now_add=True)),
                ("UpdatedTime", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user to whom this defect is currently assigned. Can be null if unassigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_defects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeveloperMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("defects_fixed", models.PositiveIntegerField(default=0)),
                ("defects_reopened", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
