# Generated by Django 6.0.4 on 2026-04-28 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_alter_defectreport_createdtime_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time this comment was posted.'),
        ),
    ]
