# Generated by Django 6.0.3 on 2026-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0004_defectreport_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defectreport",
            name="Priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defectreport",
            name="Severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Critical", "Critical"),
                    ("Major", "Major"),
                    ("Minor", "Minor"),
                    ("Low", "Low"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
