# Generated by Django 6.0.4 on 2026-04-24 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0006_developermetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='Status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Assigned', 'Assigned'), ('Cannot reproduce', 'Cannot reproduce'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened')], default='New', help_text='Current status of the defect report.', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The user to whom this defect is currently assigned. Can be null if unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL),
        ),
    ]
