# Generated by Django 6.0.4 on 2026-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0007_alter_defectreport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='Description',
            field=models.CharField(help_text='A detailed description of the defect.', max_length=200),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Email',
            field=models.EmailField(blank=True, help_text='Contact email for the tester, optional.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Priority',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='The priority level of the defect.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='ProductID',
            field=models.CharField(help_text='Unique identifier for the product associated.', max_length=30),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='ReportTitle',
            field=models.CharField(help_text='A brief title for the defect report.', max_length=30),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Severity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Low', 'Low')], help_text='The severity level of the defect.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Steps',
            field=models.TextField(help_text='The steps to reproduce the defect.'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='TesterID',
            field=models.CharField(help_text='The ID of the tester who submitted the report.', max_length=30),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Version',
            field=models.CharField(help_text='The version of the product the report is applicable to.', max_length=30),
        ),
    ]
