# Generated by Django 6.0.3 on 2026-03-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_post_delete_post"),
        ("defects", "0005_alter_defectreport_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="defect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="defects.defectreport",
            ),
        ),
    ]
