# Generated by Django 6.0.4 on 2026-04-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_author_alter_comment_text'),
        ('defects', '0008_alter_defectreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the comment was created.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='defect',
            field=models.ForeignKey(help_text='The defect report this comment is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defectreport'),
        ),
    ]
