# Generated by Django 6.0.4 on 2026-04-09 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Complete', 'Complete')], default='In progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
