# Generated by Django 6.0.4 on 2026-04-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Unique identifier for the product.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="The current version of the product.", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the product.", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In progress", "In progress"),
                            ("Complete", "Complete"),
                        ],
                        default="In progress",
                        help_text="The release status of the product.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the product was created.",
                    ),
                ),
                (
                    "product_owner",
                    models.ForeignKey(
                        help_text="The user who owns this product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
