# Generated by Django 6.0.4 on 2026-04-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_owner",
            field=models.OneToOneField(
                help_text="The user who owns this product.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DeveloperAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "developer",
                    models.OneToOneField(
                        help_text="User assigned as a developer to exactly one product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this developer is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_assignments",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
