# Generated by Django 6.0.4 on 2026-04-25 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the product was created.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(help_text='Unique identifier for the product.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_owner',
            field=models.ForeignKey(help_text='The user who owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Complete', 'Complete')], default='In progress', help_text='The release status of the product.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.CharField(help_text='The current version of the product.', max_length=20),
        ),
    ]
