# Generated by Django 6.0.3 on 2026-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_alter_defectreport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectreport',
            name='AssignedPerson',
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
