# Generated by Django 6.0.3 on 2026-03-25 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betatrax', 'creategroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('LOW', 'Low')], default='MINOR', max_length=10),
        ),
        migrations.AlterField(
            model_name='betatester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to='betatrax.betatester'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='report_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPENED', 'Opened'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
